name: python execution
on: workflow_dispatch

jobs:
  python_execution:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: python_setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: run python file
        run: python script.py 5
